Repository The-Loqui-Project/Loqui, pull requests merged in 2025-04, with the labels that each got.

#4 feat(frontend): improvements to translation interface
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/components/country-flag-polyfill.tsx
  apps/web/components/projects/language-search.tsx
  apps/web/components/projects/project-strings-list.tsx
  apps/web/components/projects/proposals/navigation-header.tsx
  apps/web/components/projects/proposals/proposal-card.tsx
  apps/web/components/projects/proposals/proposal-list.tsx
  apps/web/components/projects/proposals/translation-form.tsx
  apps/web/components/projects/proposals/types.ts
  apps/web/components/projects/search/search-bar.tsx
  apps/web/components/projects/search/search-modal.tsx
  apps/web/components/projects/search/search-result-item.tsx
  apps/web/components/projects/search/search-results.tsx
  apps/web/components/projects/translation-interface.tsx
  apps/web/lib/api-client.ts
  apps/web/lib/utils.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: enhancement

#19 Add Dockerfile for entire turborepo
  .github/workflows/build_and_push_docker_images_to_container_registry.yml
  Dockerfile
  apps/api/Dockerfile
Labels: enhancement

#23 Set Git's line ending conversions for `text` to `auto`
  .gitattributes
Labels: enhancement

#22 chore: update axios to ^1.8.4 (CVE-2024-39338)
  apps/api/package.json
  pnpm-lock.yaml
Labels: bug

#30 Fix the height of the authentication page being too large
  apps/web/app/auth/page.tsx
Labels: bug

#31 Fix the URL of the secondary login button on the home page
  apps/web/app/page.tsx
Labels: bug

#32 Add favicon
  apps/web/app/android-chrome-192x192.png
  apps/web/app/android-chrome-512x512.png
  apps/web/app/apple-touch-icon.png
  apps/web/app/favicon-16x16.png
  apps/web/app/favicon-32x32.png
  apps/web/app/favicon.ico
  apps/web/app/site.webmanifest
  docs/media/icon_1028x1028.png
Labels: enhancement

#35 Fix the footer not being anchored to the bottom of the page
  apps/web/app/project/[id]/layout.tsx
Labels: bug

#38 feat: proper task scheduling using websockets
  apps/api/package.json
  apps/api/routes/index.ts
  apps/api/routes/v1/projects/management/opt-in.ts
  apps/api/routes/v1/tasks/get.ts
  apps/api/routes/v1/tasks/list.ts
  apps/api/server.ts
  apps/api/util/jobs/index.ts
  apps/api/util/jobs/projects.ts
  apps/api/util/modrinth.ts
  apps/api/util/task-manager.ts
  apps/api/util/websocket-server.ts
  apps/web/app/auth/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/projects/opt-in-modal.tsx
  apps/web/contexts/task-context.tsx
  apps/web/hooks/use-task.tsx
  apps/web/lib/api-client.ts
  apps/web/lib/ws-client.ts
  pnpm-lock.yaml
Labels: enhancement

#45 ci: better ci
  .github/workflows/build_api.yml
  .github/workflows/build_web.yml
Labels: enhancement

#53 fix(web): fix home cta main button (bottom)
  apps/web/app/page.tsx
Labels: bug

#51 feat(web): redesign footer and add links and resources
  apps/web/components/homepage/footer.tsx
  apps/web/components/ui/icons/discord-icon.tsx
  apps/web/components/ui/icons/github-icon.tsx
  apps/web/components/ui/icons/modrinth-icon.tsx
  apps/web/components/ui/icons/modrinthIcon.tsx
Labels: enhancement

#58 chore: move loqui-icon.tsx to @/components/ui/icons
  apps/web/components/homepage/footer.tsx
  apps/web/components/homepage/navbar.tsx
  apps/web/components/ui/icons/loqui-icon.tsx
  apps/web/lib/api-client.ts
Labels: enhancement

#52 feat: reporting frontend
  apps/api/db/drizzle/0002_fair_agent_zero.sql
  apps/api/db/drizzle/0003_simple_multiple_man.sql
  apps/api/db/drizzle/0004_flippant_wild_pack.sql
  apps/api/db/drizzle/meta/0002_snapshot.json
  apps/api/db/drizzle/meta/0003_snapshot.json
  apps/api/db/drizzle/meta/0004_snapshot.json
  apps/api/db/drizzle/meta/_journal.json
  apps/api/db/schema/schema.ts
  apps/api/routes/index.ts
  apps/api/routes/v1/auth/user.ts
  apps/api/routes/v1/projects/[id]/report.ts
  apps/api/routes/v1/projects/management/opt-out.ts
  apps/api/routes/v1/projects/reports/list.ts
  apps/api/routes/v1/projects/reports/resolve.ts
  apps/api/routes/v1/proposals/report-string.ts
  apps/api/routes/v1/proposals/report.ts
  apps/api/routes/v1/proposals/reset-votes.ts
  apps/api/routes/v1/strings/reports/list.ts
  apps/api/routes/v1/strings/reports/resolve.ts
  apps/web/app/dashboard/page.tsx
  apps/web/app/moderation/page.tsx
  apps/web/app/project/[id]/layout.tsx
  apps/web/components/homepage/project-card.tsx
  apps/web/components/moderation/project-report-action-modal.tsx
  apps/web/components/moderation/proposal-report-action-modal.tsx
  apps/web/components/moderation/report-table.tsx
  apps/web/components/moderation/string-report-action-modal.tsx
  apps/web/components/projects/project-report-modal.tsx
  apps/web/components/projects/proposals/proposal-card.tsx
  apps/web/components/projects/proposals/proposal-report-modal.tsx
  apps/web/components/projects/proposals/string-report-modal.tsx
  apps/web/components/projects/proposals/translation-form.tsx
  apps/web/lib/api-client-wrapper.ts
  apps/web/lib/api-client.ts
Labels: enhancement

#71 fix(web): remove duplicate X from search-modal.tsx
  apps/web/components/projects/search/search-modal.tsx
Labels: bug

#77 chore: update .gitattributes for line ending normalization
  .gitattributes
Labels: bug, enhancement

#81 fix(db): migrations not being included in the Docker image
  Dockerfile
  apps/api/package.json
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: bug, ci

#83 feat(web): :sparkles: Go to the next string on proposal submit
  apps/web/components/projects/translation-interface.tsx
Labels: enhancement

#84 refactor(db): :fire: Reset the database migrations
  apps/api/db/drizzle/0000_special_shaman.sql
  apps/api/db/drizzle/0001_left_veda.sql
  apps/api/db/drizzle/0002_fair_agent_zero.sql
  apps/api/db/drizzle/0002_wandering_sir_ram.sql
  apps/api/db/drizzle/0003_simple_multiple_man.sql
  apps/api/db/drizzle/0003_thin_titania.sql
  apps/api/db/drizzle/0004_flippant_wild_pack.sql
  apps/api/db/drizzle/meta/0000_snapshot.json
  apps/api/db/drizzle/meta/0001_snapshot.json
  apps/api/db/drizzle/meta/0002_snapshot.json
  apps/api/db/drizzle/meta/0003_snapshot.json
  apps/api/db/drizzle/meta/0004_snapshot.json
  apps/api/db/drizzle/meta/_journal.json
Labels: enhancement

#85 fix(web): :bug: Add missing bounds check and fetch project progress on translation save/delete
  apps/web/components/projects/translation-interface.tsx
Labels: bug
